apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

resources:
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app: postgres
      app.kubernetes.io/name: postgres
      app.kubernetes.io/part-of: platform
    includeSelectors: true

configMapGenerator:
  - name: postgres-init
    files:
      - files/init-databases.sh
