apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init
data:
  init-databases.sh: |
    #!/bin/bash
    set -e
    {{- range .Values.initDatabases }}
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
      SELECT 'CREATE DATABASE {{ . }}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '{{ . }}')\gexec
    EOSQL
    {{- end }}
